// <auto-generated>
/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using RankVectors.Client;

namespace RankVectors.com.rankvectors.model
{
    /// <summary>
    /// GenerateSuggestionsRequest
    /// </summary>
    public partial class GenerateSuggestionsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateSuggestionsRequest" /> class.
        /// </summary>
        /// <param name="minRelevanceScore">Minimum relevance score for suggestions</param>
        [JsonConstructor]
        public GenerateSuggestionsRequest(Option<decimal?> minRelevanceScore = default)
        {
            MinRelevanceScoreOption = minRelevanceScore;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of MinRelevanceScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> MinRelevanceScoreOption { get; private set; }

        /// <summary>
        /// Minimum relevance score for suggestions
        /// </summary>
        /// <value>Minimum relevance score for suggestions</value>
        /* <example>0.7</example> */
        [JsonPropertyName("minRelevanceScore")]
        public decimal? MinRelevanceScore { get { return this.MinRelevanceScoreOption; } set { this.MinRelevanceScoreOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenerateSuggestionsRequest {\n");
            sb.Append("  MinRelevanceScore: ").Append(MinRelevanceScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MinRelevanceScore (decimal) maximum
            if (this.MinRelevanceScoreOption.IsSet && this.MinRelevanceScoreOption.Value > (decimal)1)
            {
                yield return new ValidationResult("Invalid value for MinRelevanceScore, must be a value less than or equal to 1.", new [] { "MinRelevanceScore" });
            }

            // MinRelevanceScore (decimal) minimum
            if (this.MinRelevanceScoreOption.IsSet && this.MinRelevanceScoreOption.Value < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for MinRelevanceScore, must be a value greater than or equal to 0.", new [] { "MinRelevanceScore" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GenerateSuggestionsRequest" />
    /// </summary>
    public class GenerateSuggestionsRequestJsonConverter : JsonConverter<GenerateSuggestionsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GenerateSuggestionsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GenerateSuggestionsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> minRelevanceScore = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "minRelevanceScore":
                            minRelevanceScore = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (minRelevanceScore.IsSet && minRelevanceScore.Value == null)
                throw new ArgumentNullException(nameof(minRelevanceScore), "Property is not nullable for class GenerateSuggestionsRequest.");

            return new GenerateSuggestionsRequest(minRelevanceScore);
        }

        /// <summary>
        /// Serializes a <see cref="GenerateSuggestionsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="generateSuggestionsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GenerateSuggestionsRequest generateSuggestionsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, generateSuggestionsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GenerateSuggestionsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="generateSuggestionsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GenerateSuggestionsRequest generateSuggestionsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (generateSuggestionsRequest.MinRelevanceScoreOption.IsSet)
                writer.WriteNumber("minRelevanceScore", generateSuggestionsRequest.MinRelevanceScoreOption.Value!.Value);
        }
    }
}
