// <auto-generated>
/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using RankVectors.Client;

namespace RankVectors.com.rankvectors.model
{
    /// <summary>
    /// ListImplementations200Response
    /// </summary>
    public partial class ListImplementations200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListImplementations200Response" /> class.
        /// </summary>
        /// <param name="success">success</param>
        /// <param name="implementations">implementations</param>
        /// <param name="count">Number of implementations returned</param>
        /// <param name="filters">Applied filters</param>
        [JsonConstructor]
        public ListImplementations200Response(Option<bool?> success = default, Option<List<Implementation>?> implementations = default, Option<int?> count = default, Option<Object?> filters = default)
        {
            SuccessOption = success;
            ImplementationsOption = implementations;
            CountOption = count;
            FiltersOption = filters;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Success
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SuccessOption { get; private set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("success")]
        public bool? Success { get { return this.SuccessOption; } set { this.SuccessOption = new(value); } }

        /// <summary>
        /// Used to track the state of Implementations
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Implementation>?> ImplementationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Implementations
        /// </summary>
        [JsonPropertyName("implementations")]
        public List<Implementation>? Implementations { get { return this.ImplementationsOption; } set { this.ImplementationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Count
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CountOption { get; private set; }

        /// <summary>
        /// Number of implementations returned
        /// </summary>
        /// <value>Number of implementations returned</value>
        /* <example>25</example> */
        [JsonPropertyName("count")]
        public int? Count { get { return this.CountOption; } set { this.CountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Filters
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> FiltersOption { get; private set; }

        /// <summary>
        /// Applied filters
        /// </summary>
        /// <value>Applied filters</value>
        [JsonPropertyName("filters")]
        public Object? Filters { get { return this.FiltersOption; } set { this.FiltersOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListImplementations200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Implementations: ").Append(Implementations).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListImplementations200Response" />
    /// </summary>
    public class ListImplementations200ResponseJsonConverter : JsonConverter<ListImplementations200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="ListImplementations200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListImplementations200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<List<Implementation>?> implementations = default;
            Option<int?> count = default;
            Option<Object?> filters = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "implementations":
                            implementations = new Option<List<Implementation>?>(JsonSerializer.Deserialize<List<Implementation>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "filters":
                            filters = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class ListImplementations200Response.");

            if (implementations.IsSet && implementations.Value == null)
                throw new ArgumentNullException(nameof(implementations), "Property is not nullable for class ListImplementations200Response.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class ListImplementations200Response.");

            if (filters.IsSet && filters.Value == null)
                throw new ArgumentNullException(nameof(filters), "Property is not nullable for class ListImplementations200Response.");

            return new ListImplementations200Response(success, implementations, count, filters);
        }

        /// <summary>
        /// Serializes a <see cref="ListImplementations200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listImplementations200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListImplementations200Response listImplementations200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listImplementations200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListImplementations200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listImplementations200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListImplementations200Response listImplementations200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listImplementations200Response.ImplementationsOption.IsSet && listImplementations200Response.Implementations == null)
                throw new ArgumentNullException(nameof(listImplementations200Response.Implementations), "Property is required for class ListImplementations200Response.");

            if (listImplementations200Response.FiltersOption.IsSet && listImplementations200Response.Filters == null)
                throw new ArgumentNullException(nameof(listImplementations200Response.Filters), "Property is required for class ListImplementations200Response.");

            if (listImplementations200Response.SuccessOption.IsSet)
                writer.WriteBoolean("success", listImplementations200Response.SuccessOption.Value!.Value);

            if (listImplementations200Response.ImplementationsOption.IsSet)
            {
                writer.WritePropertyName("implementations");
                JsonSerializer.Serialize(writer, listImplementations200Response.Implementations, jsonSerializerOptions);
            }
            if (listImplementations200Response.CountOption.IsSet)
                writer.WriteNumber("count", listImplementations200Response.CountOption.Value!.Value);

            if (listImplementations200Response.FiltersOption.IsSet)
            {
                writer.WritePropertyName("filters");
                JsonSerializer.Serialize(writer, listImplementations200Response.Filters, jsonSerializerOptions);
            }
        }
    }
}
