// <auto-generated>
/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using RankVectors.Client;

namespace RankVectors.com.rankvectors.model
{
    /// <summary>
    /// PageInfo
    /// </summary>
    public partial class PageInfo : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PageInfo" /> class.
        /// </summary>
        /// <param name="url">Page URL</param>
        /// <param name="title">Page title</param>
        /// <param name="description">Page description</param>
        /// <param name="wordCount">Page word count</param>
        [JsonConstructor]
        public PageInfo(string url, string title, Option<string?> description = default, Option<int?> wordCount = default)
        {
            Url = url;
            Title = title;
            DescriptionOption = description;
            WordCountOption = wordCount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Page URL
        /// </summary>
        /// <value>Page URL</value>
        /* <example>https://example.com/page</example> */
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Page title
        /// </summary>
        /// <value>Page title</value>
        /* <example>Page Title</example> */
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Page description
        /// </summary>
        /// <value>Page description</value>
        /* <example>Page description</example> */
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of WordCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> WordCountOption { get; private set; }

        /// <summary>
        /// Page word count
        /// </summary>
        /// <value>Page word count</value>
        /* <example>500</example> */
        [JsonPropertyName("wordCount")]
        public int? WordCount { get { return this.WordCountOption; } set { this.WordCountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PageInfo {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  WordCount: ").Append(WordCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PageInfo" />
    /// </summary>
    public class PageInfoJsonConverter : JsonConverter<PageInfo>
    {
        /// <summary>
        /// Deserializes json to <see cref="PageInfo" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PageInfo Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<string?> title = default;
            Option<string?> description = default;
            Option<int?> wordCount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wordCount":
                            wordCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class PageInfo.", nameof(url));

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class PageInfo.", nameof(title));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class PageInfo.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class PageInfo.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class PageInfo.");

            if (wordCount.IsSet && wordCount.Value == null)
                throw new ArgumentNullException(nameof(wordCount), "Property is not nullable for class PageInfo.");

            return new PageInfo(url.Value!, title.Value!, description, wordCount);
        }

        /// <summary>
        /// Serializes a <see cref="PageInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pageInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PageInfo pageInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pageInfo, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PageInfo" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pageInfo"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PageInfo pageInfo, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pageInfo.Url == null)
                throw new ArgumentNullException(nameof(pageInfo.Url), "Property is required for class PageInfo.");

            if (pageInfo.Title == null)
                throw new ArgumentNullException(nameof(pageInfo.Title), "Property is required for class PageInfo.");

            if (pageInfo.DescriptionOption.IsSet && pageInfo.Description == null)
                throw new ArgumentNullException(nameof(pageInfo.Description), "Property is required for class PageInfo.");

            writer.WriteString("url", pageInfo.Url);

            writer.WriteString("title", pageInfo.Title);

            if (pageInfo.DescriptionOption.IsSet)
                writer.WriteString("description", pageInfo.Description);

            if (pageInfo.WordCountOption.IsSet)
                writer.WriteNumber("wordCount", pageInfo.WordCountOption.Value!.Value);
        }
    }
}
