// <auto-generated>
/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using RankVectors.Client;

namespace RankVectors.com.rankvectors.model
{
    /// <summary>
    /// Count of related entities
    /// </summary>
    public partial class ProjectCount : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectCount" /> class.
        /// </summary>
        /// <param name="pages">pages</param>
        /// <param name="suggestions">suggestions</param>
        [JsonConstructor]
        public ProjectCount(Option<int?> pages = default, Option<int?> suggestions = default)
        {
            PagesOption = pages;
            SuggestionsOption = suggestions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Pages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pages
        /// </summary>
        /* <example>150</example> */
        [JsonPropertyName("pages")]
        public int? Pages { get { return this.PagesOption; } set { this.PagesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Suggestions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SuggestionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Suggestions
        /// </summary>
        /* <example>25</example> */
        [JsonPropertyName("suggestions")]
        public int? Suggestions { get { return this.SuggestionsOption; } set { this.SuggestionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProjectCount {\n");
            sb.Append("  Pages: ").Append(Pages).Append("\n");
            sb.Append("  Suggestions: ").Append(Suggestions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProjectCount" />
    /// </summary>
    public class ProjectCountJsonConverter : JsonConverter<ProjectCount>
    {
        /// <summary>
        /// Deserializes json to <see cref="ProjectCount" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProjectCount Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> pages = default;
            Option<int?> suggestions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "pages":
                            pages = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "suggestions":
                            suggestions = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (pages.IsSet && pages.Value == null)
                throw new ArgumentNullException(nameof(pages), "Property is not nullable for class ProjectCount.");

            if (suggestions.IsSet && suggestions.Value == null)
                throw new ArgumentNullException(nameof(suggestions), "Property is not nullable for class ProjectCount.");

            return new ProjectCount(pages, suggestions);
        }

        /// <summary>
        /// Serializes a <see cref="ProjectCount" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectCount"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProjectCount projectCount, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, projectCount, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProjectCount" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="projectCount"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProjectCount projectCount, JsonSerializerOptions jsonSerializerOptions)
        {
            if (projectCount.PagesOption.IsSet)
                writer.WriteNumber("pages", projectCount.PagesOption.Value!.Value);

            if (projectCount.SuggestionsOption.IsSet)
                writer.WriteNumber("suggestions", projectCount.SuggestionsOption.Value!.Value);
        }
    }
}
