// <auto-generated>
/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using RankVectors.Client;

namespace RankVectors.com.rankvectors.model
{
    /// <summary>
    /// RollbackImplementation200Response
    /// </summary>
    public partial class RollbackImplementation200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RollbackImplementation200Response" /> class.
        /// </summary>
        /// <param name="success">success</param>
        /// <param name="creditsRefunded">Credits refunded (50% of implementation cost)</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public RollbackImplementation200Response(Option<bool?> success = default, Option<decimal?> creditsRefunded = default, Option<string?> message = default)
        {
            SuccessOption = success;
            CreditsRefundedOption = creditsRefunded;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Success
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SuccessOption { get; private set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("success")]
        public bool? Success { get { return this.SuccessOption; } set { this.SuccessOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreditsRefunded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> CreditsRefundedOption { get; private set; }

        /// <summary>
        /// Credits refunded (50% of implementation cost)
        /// </summary>
        /// <value>Credits refunded (50% of implementation cost)</value>
        /* <example>0.5</example> */
        [JsonPropertyName("creditsRefunded")]
        public decimal? CreditsRefunded { get { return this.CreditsRefundedOption; } set { this.CreditsRefundedOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /* <example>Successfully rolled back implementation. 0.5 credits refunded.</example> */
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RollbackImplementation200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  CreditsRefunded: ").Append(CreditsRefunded).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RollbackImplementation200Response" />
    /// </summary>
    public class RollbackImplementation200ResponseJsonConverter : JsonConverter<RollbackImplementation200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="RollbackImplementation200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RollbackImplementation200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<decimal?> creditsRefunded = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "creditsRefunded":
                            creditsRefunded = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class RollbackImplementation200Response.");

            if (creditsRefunded.IsSet && creditsRefunded.Value == null)
                throw new ArgumentNullException(nameof(creditsRefunded), "Property is not nullable for class RollbackImplementation200Response.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class RollbackImplementation200Response.");

            return new RollbackImplementation200Response(success, creditsRefunded, message);
        }

        /// <summary>
        /// Serializes a <see cref="RollbackImplementation200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rollbackImplementation200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RollbackImplementation200Response rollbackImplementation200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rollbackImplementation200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RollbackImplementation200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rollbackImplementation200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RollbackImplementation200Response rollbackImplementation200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rollbackImplementation200Response.MessageOption.IsSet && rollbackImplementation200Response.Message == null)
                throw new ArgumentNullException(nameof(rollbackImplementation200Response.Message), "Property is required for class RollbackImplementation200Response.");

            if (rollbackImplementation200Response.SuccessOption.IsSet)
                writer.WriteBoolean("success", rollbackImplementation200Response.SuccessOption.Value!.Value);

            if (rollbackImplementation200Response.CreditsRefundedOption.IsSet)
                writer.WriteNumber("creditsRefunded", rollbackImplementation200Response.CreditsRefundedOption.Value!.Value);

            if (rollbackImplementation200Response.MessageOption.IsSet)
                writer.WriteString("message", rollbackImplementation200Response.Message);
        }
    }
}
