// <auto-generated>
/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using RankVectors.Client;

namespace RankVectors.com.rankvectors.model
{
    /// <summary>
    /// Rollback
    /// </summary>
    public partial class Rollback : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rollback" /> class.
        /// </summary>
        /// <param name="id">Unique rollback identifier</param>
        /// <param name="reason">Reason for rollback</param>
        /// <param name="createdAt">Rollback timestamp</param>
        /// <param name="creditsRefunded">Credits refunded</param>
        [JsonConstructor]
        public Rollback(string id, string reason, DateTime createdAt, Option<decimal?> creditsRefunded = default)
        {
            Id = id;
            Reason = reason;
            CreatedAt = createdAt;
            CreditsRefundedOption = creditsRefunded;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Unique rollback identifier
        /// </summary>
        /// <value>Unique rollback identifier</value>
        /* <example>rollback-123</example> */
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Reason for rollback
        /// </summary>
        /// <value>Reason for rollback</value>
        /* <example>Incorrect link placement</example> */
        [JsonPropertyName("reason")]
        public string Reason { get; set; }

        /// <summary>
        /// Rollback timestamp
        /// </summary>
        /// <value>Rollback timestamp</value>
        /* <example>2025-01-15T10:00Z</example> */
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of CreditsRefunded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> CreditsRefundedOption { get; private set; }

        /// <summary>
        /// Credits refunded
        /// </summary>
        /// <value>Credits refunded</value>
        /* <example>0.5</example> */
        [JsonPropertyName("creditsRefunded")]
        public decimal? CreditsRefunded { get { return this.CreditsRefundedOption; } set { this.CreditsRefundedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rollback {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CreditsRefunded: ").Append(CreditsRefunded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Rollback" />
    /// </summary>
    public class RollbackJsonConverter : JsonConverter<Rollback>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Rollback" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Rollback Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> reason = default;
            Option<DateTime?> createdAt = default;
            Option<decimal?> creditsRefunded = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "creditsRefunded":
                            creditsRefunded = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Rollback.", nameof(id));

            if (!reason.IsSet)
                throw new ArgumentException("Property is required for class Rollback.", nameof(reason));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Rollback.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Rollback.");

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class Rollback.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Rollback.");

            if (creditsRefunded.IsSet && creditsRefunded.Value == null)
                throw new ArgumentNullException(nameof(creditsRefunded), "Property is not nullable for class Rollback.");

            return new Rollback(id.Value!, reason.Value!, createdAt.Value!.Value!, creditsRefunded);
        }

        /// <summary>
        /// Serializes a <see cref="Rollback" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rollback"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Rollback rollback, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rollback, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Rollback" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rollback"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Rollback rollback, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rollback.Id == null)
                throw new ArgumentNullException(nameof(rollback.Id), "Property is required for class Rollback.");

            if (rollback.Reason == null)
                throw new ArgumentNullException(nameof(rollback.Reason), "Property is required for class Rollback.");

            writer.WriteString("id", rollback.Id);

            writer.WriteString("reason", rollback.Reason);

            writer.WriteString("createdAt", rollback.CreatedAt.ToString(CreatedAtFormat));

            if (rollback.CreditsRefundedOption.IsSet)
                writer.WriteNumber("creditsRefunded", rollback.CreditsRefundedOption.Value!.Value);
        }
    }
}
