/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RankVectors.com.rankvectors.model;
using RankVectors.Client;
using System.Reflection;

namespace RankVectors.Test.Model
{
    /// <summary>
    ///  Class for testing CreditBalance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditBalanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditBalance
        //private CreditBalance instance;

        public CreditBalanceTests()
        {
            // TODO uncomment below to create an instance of CreditBalance
            //instance = new CreditBalance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditBalance
        /// </summary>
        [Fact]
        public void CreditBalanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreditBalance
            //Assert.IsType<CreditBalance>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'PageLimit'
        /// </summary>
        [Fact]
        public void PageLimitTest()
        {
            // TODO unit test for the property 'PageLimit'
        }

        /// <summary>
        /// Test the property 'SpendingLimit'
        /// </summary>
        [Fact]
        public void SpendingLimitTest()
        {
            // TODO unit test for the property 'SpendingLimit'
        }

        /// <summary>
        /// Test the property 'AutoRecharge'
        /// </summary>
        [Fact]
        public void AutoRechargeTest()
        {
            // TODO unit test for the property 'AutoRecharge'
        }

        /// <summary>
        /// Test the property 'CurrentPeriod'
        /// </summary>
        [Fact]
        public void CurrentPeriodTest()
        {
            // TODO unit test for the property 'CurrentPeriod'
        }

        /// <summary>
        /// Test the property 'UsageHistory'
        /// </summary>
        [Fact]
        public void UsageHistoryTest()
        {
            // TODO unit test for the property 'UsageHistory'
        }
    }
}
